version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb:/data/db


  server:
    build: ./task-server
    ports:
      - "3000:3000"
    restart: always
    environment:
      - ENV=test
    links:
      - mongo


