mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - /usr/local/var/mongodb:/data/db


server:
  build: ./task-server
  dockerfile: Dockerfile
  ports:
    - "3000:3000"
  restart: always
  links:
    - mongo

